### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by juraj-hrivnak** [xemnes/CookingForBlockheads#1] opened 2023-01-16 22:05 UTC
### The issue

The buttons on the right side of the recipe table GUI are broken.

![2023-01-16_21 22 48](https://user-images.githubusercontent.com/71150936/212772112-0e74f56b-cc10-41b9-8a1f-2718a16118e0.png)

**Comment by Desoroxxx** [comment] 2023-01-21 21:56
If you create a new world with Cooking For Blockhead (https://shor.cz/cfbh) instead of Delightfull Cuisine For Woodhead does this still happen?

**Comment by juraj-hrivnak** [comment] 2023-03-01 01:00
Yes, it does. Sorry for the reply.
@xemnes

**Comment by xemnes** [comment] 2023-03-01 01:03
i think i know what the issue is, i had modified the texture of the gui to look a little better than vanilla, this also included some code changes to change the uv texture corrodinates. it seems i didnt include it properly in the build, i will fix this.

**Comment by xemnes** [comment] 2023-03-01 01:13
ok so i just looked into it, i dont see any problems with the build i uploaded to curseforge. also looking at your screenshot, i see that its using the old texture. the buttons should not look like that
![image](https://user-images.githubusercontent.com/603338/222019343-5f7e1c66-45ba-44ad-a7cd-43754bbbee1b.png)
are you using a resource pack that may change textures for cookingforblockheads? if so can you go into said resource pack and go to "assets\cookingforblockheads\textures\gui" and delete gui.png

**Comment by juraj-hrivnak** [comment] 2023-03-01 01:16
Oh, yes, I use the Modernity resource pack.

**Comment by xemnes** [comment] 2023-03-01 01:17
ah yes, just checked the modernity resource pack and it does indeed change the gui texture, you will have to delete it from the resource pack in order for it to look correct. double check this fixes it and i will close this issue.

**Comment by juraj-hrivnak** [comment] 2023-03-01 01:18
Okay, thanks! That was simple!

**Closed as completed** 2023-03-01 01:18 UTC
